# Generated by Django 4.1 on 2023-11-29 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("type", models.CharField(max_length=255)),
                ("power", models.CharField(max_length=255)),
                ("current", models.CharField(max_length=255)),
                ("voltage", models.CharField(max_length=255)),
                ("serial_number", models.CharField(max_length=255)),
                ("comment", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MeasurementValues",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wavelength", models.FloatField()),
                ("amplitude", models.FloatField()),
                (
                    "measurement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurement_values",
                        to="pages.measurement",
                    ),
                ),
            ],
        ),
    ]
