# Generated by Django 4.1 on 2023-11-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_rename_current_measurement_current_ma_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurement",
            name="current_mA",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="set_power_W",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="voltage_V",
            field=models.FloatField(),
        ),
    ]
